version: '3.6'

services:
  minecraft:
    build: .
    image: lysz210/minecraft-armv7:1.15.2
    environment:
      - EULA=true
    volumes:
      - ./minecraft:/minecraft
    ports:
      - "25565:25565"