version: "3.3"

services:
  minecraft:
    build: .
    image: lysz210/minecraft:1.16.1
    environment:
      - EULA=true
      - JAVA_OPTS=-Xmx512M -Xms512M
    volumes:
      - ./minecraft:/minecraft
    ports:
      - "25565:25565"